import io
import os
import re
from datetime import date

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image

from models import db, Student, Subject, Enrollment, LabMarks
from final_result_utils import recalculate_lab_result
from batch_utils import clean_filter, apply_student_batch_filters, batch_label

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LEFT_LOGO = os.path.join(BASE_DIR, "static", "images", "left_logo.jpg")
RIGHT_LOGO = os.path.join(BASE_DIR, "static", "images", "right_logo.png")

TNR = "Times-Roman"
TNR_BOLD = "Times-Bold"
TNR_ITALIC = "Times-Italic"
BLACK = colors.black
LIGHT_GRAY = colors.HexColor("#F2F3F4")
LIGHT_BLUE = colors.HexColor("#D6EAF8")
GREEN = colors.HexColor("#D5F5E3")
RED = colors.HexColor("#FADBD8")
YELLOW = colors.HexColor("#FFF3CD")


def _style(name, size=8, bold=False, align=TA_CENTER, leading=None):
    return ParagraphStyle(
        name=name,
        fontName=TNR_BOLD if bold else TNR,
        fontSize=size,
        alignment=align,
        leading=leading or size + 3,
        textColor=BLACK,
    )


def _sanitize(name):
    name = str(name or "").strip()
    name = re.sub(r"[^\w\s-]", "", name)
    name = re.sub(r"[\s]+", "_", name)
    return name or "Lab"


def _fmt(v):
    if v is None:
        return "-"
    try:
        fv = float(v)
        return str(int(fv)) if fv == int(fv) else str(round(fv, 2))
    except Exception:
        return str(v)


def build_lab_report_data(subject_code, semester_id, academic_year, division="", batch=""):
    subj = Subject.query.get(subject_code)
    if not subj:
        return [], {}

    students_query = (
        db.session.query(Student)
        .join(Enrollment, Enrollment.prn == Student.prn)
        .filter(
            Enrollment.subject_code == subject_code,
            Enrollment.semester_id == semester_id,
            Enrollment.academic_year == academic_year,
        )
    )
    students_query = apply_student_batch_filters(students_query, Student, division, batch)
    students = students_query.order_by(Student.prn).all()

    marks_rows = LabMarks.query.filter_by(
        subject_code=subject_code,
        semester_id=semester_id,
        academic_year=academic_year,
    ).all()
    lookup = {m.prn: m for m in marks_rows}

    data = []
    for sr, stu in enumerate(students, 1):
        lm = lookup.get(stu.prn)

        ca1 = ca2 = internal = external = total = grade = grade_point = None
        status = "PENDING"

        if lm:
            recalculate_lab_result(lm)
            ca1 = getattr(lm, "ca1", None)
            ca2 = getattr(lm, "ca2", None)
            internal = lm.internal
            external = lm.external
            total = lm.total_marks
            grade = lm.grade
            grade_point = lm.grade_point
            if lm.is_passed is True:
                status = "PASS"
            elif lm.is_passed is False:
                status = "FAIL"

        data.append({
            "sr": sr,
            "prn": stu.prn,
            "name": stu.name,
            "ca1": float(ca1) if ca1 is not None else None,
            "ca2": float(ca2) if ca2 is not None else None,
            "internal": float(internal) if internal is not None else None,
            "external": float(external) if external is not None else None,
            "total": float(total) if total is not None else None,
            "grade": grade or "-",
            "grade_point": float(grade_point) if grade_point is not None else None,
            "status": status,
        })

    meta = {
        "subject_code": subj.subject_code,
        "subject_name": subj.subject_name,
        "semester_id": semester_id,
        "academic_year": academic_year,
        "credits": subj.credits,
        "subject_type": subj.subject_type,
        "division": clean_filter(division),
        "batch": clean_filter(batch),
        "batch_label": batch_label(division, batch),
    }
    return data, meta


def _footer(canvas, doc):
    canvas.saveState()
    w, h = landscape(A4)
    canvas.setFont(TNR_ITALIC, 8)
    canvas.setFillColor(colors.HexColor("#444444"))
    canvas.drawString(1.2 * cm, 0.35 * cm, "Generated by ECE Student Management System - CSMSS Chh. Shahu College of Engineering")
    canvas.drawRightString(w - 1.2 * cm, 0.35 * cm, f"Page {doc.page} | {date.today().strftime('%d %B %Y')}")
    canvas.restoreState()


def _common_pdf_header(width):
    s_title = _style("lab_title", size=13, bold=True, align=TA_CENTER, leading=17)
    left_logo = Image(LEFT_LOGO, width=55, height=55) if os.path.exists(LEFT_LOGO) else ""
    right_logo = Image(RIGHT_LOGO, width=55, height=55) if os.path.exists(RIGHT_LOGO) else ""

    header = Table([[left_logo, Paragraph(
        "Chhatrapati Shahu Maharaj Shikshan Sanstha's<br/>"
        "CSMSS Chh. Shahu College of Engineering<br/>"
        "Kanchanwadi, Chhatrapati Sambhajinagar - 431011<br/>"
        "Department of Electronics and Computer Engineering",
        s_title,
    ), right_logo]], colWidths=[2 * cm, width - 4 * cm, 2 * cm])
    header.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1, BLACK),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return header


def generate_lab_pdf_report(meta, data):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=landscape(A4),
        leftMargin=1.2 * cm,
        rightMargin=1.2 * cm,
        topMargin=1.2 * cm,
        bottomMargin=1.2 * cm,
    )

    page_w = landscape(A4)[0]
    usable_w = page_w - 2.4 * cm

    s_head = _style("head", size=8, bold=True)
    s_cell = _style("cell", size=8)
    s_left = _style("left", size=8, align=TA_LEFT)
    s_bold = _style("bold", size=9, bold=True)

    story = []
    story.append(_common_pdf_header(usable_w))
    story.append(Spacer(1, 8))

    title = Table([[Paragraph(
        f"LAB / PROJECT MARKS REPORT | {meta['subject_code']} - {meta['subject_name']} | Semester {meta['semester_id']} | A.Y. {meta['academic_year']} | {meta.get('batch_label', 'All Students')}",
        s_bold,
    )]], colWidths=[usable_w])
    title.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1, BLACK),
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BLUE),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(title)
    story.append(Spacer(1, 8))

    headers = ["SR", "PRN", "Student Name", "CA1 /30", "CA2 /30", "Internal /60", "External /40", "Total /100", "Grade", "GP", "Result"]
    table_data = [[Paragraph(h, s_head) for h in headers]]

    pass_c = fail_c = pending_c = 0
    totals = []

    for i, row in enumerate(data, 1):
        status = row["status"]
        if status == "PASS":
            pass_c += 1
        elif status == "FAIL":
            fail_c += 1
        else:
            pending_c += 1
        if row.get("total") is not None:
            totals.append(float(row["total"]))

        table_data.append([
            Paragraph(str(i), s_cell),
            Paragraph(row["prn"], s_cell),
            Paragraph(row["name"], s_left),
            Paragraph(_fmt(row.get("ca1")), s_cell),
            Paragraph(_fmt(row.get("ca2")), s_cell),
            Paragraph(_fmt(row.get("internal")), s_cell),
            Paragraph(_fmt(row.get("external")), s_cell),
            Paragraph(_fmt(row.get("total")), s_cell),
            Paragraph(str(row.get("grade") or "-"), s_cell),
            Paragraph(_fmt(row.get("grade_point")), s_cell),
            Paragraph(status, s_cell),
        ])

    col_widths = [1.0 * cm, 3.0 * cm, 6.2 * cm, 1.8 * cm, 1.8 * cm, 2.2 * cm, 2.2 * cm, 2.1 * cm, 1.5 * cm, 1.5 * cm, 2.0 * cm]
    table = Table(table_data, colWidths=col_widths, repeatRows=1)
    style = TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, BLACK),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E3A5F")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("ALIGN", (2, 1), (2, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ])

    for idx, row in enumerate(data, 1):
        status = row["status"]
        if status == "PASS":
            style.add("BACKGROUND", (10, idx), (10, idx), GREEN)
        elif status == "FAIL":
            style.add("BACKGROUND", (10, idx), (10, idx), RED)
        else:
            style.add("BACKGROUND", (10, idx), (10, idx), YELLOW)

    table.setStyle(style)
    story.append(table)
    story.append(Spacer(1, 12))

    avg = round(sum(totals) / len(totals), 2) if totals else "-"
    summary = Table([
        ["Total Students", "Pass", "Fail", "Pending", "Highest", "Lowest", "Average"],
        [str(len(data)), str(pass_c), str(fail_c), str(pending_c), str(max(totals)) if totals else "-", str(min(totals)) if totals else "-", str(avg)],
    ], colWidths=[usable_w / 7] * 7)
    summary.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, BLACK),
        ("BACKGROUND", (0, 0), (-1, 0), LIGHT_BLUE),
        ("FONTNAME", (0, 0), (-1, 0), TNR_BOLD),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(summary)
    story.append(Spacer(1, 25))

    sig = Table([[Paragraph("Lab Incharge", s_bold), Paragraph("Class Teacher", s_bold), Paragraph("HOD", s_bold)]], colWidths=[usable_w / 3] * 3)
    sig.setStyle(TableStyle([
        ("LINEABOVE", (0, 0), (-1, -1), 1, BLACK),
        ("TOPPADDING", (0, 0), (-1, -1), 20),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(sig)

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    buf.seek(0)
    filename = f"Lab_Report_{_sanitize(meta['subject_code'])}_Sem{meta['semester_id']}.pdf"
    return buf, filename
