import io
import statistics
import re
from datetime import date
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

LEFT_LOGO = os.path.join(BASE_DIR, "static", "images", "left_logo.jpg")
RIGHT_LOGO = os.path.join(BASE_DIR, "static", "images", "right_logo.png")

C_BLACK  = colors.HexColor("#000000")
C_HGRAY  = colors.HexColor("#808080")   # heading gray
C_DGRAY  = colors.HexColor("#444444")
C_MGRAY  = colors.HexColor("#888888")
C_LGRAY  = colors.HexColor("#E8E8E8")
C_LLGRAY = colors.HexColor("#F5F5F5")
C_WHITE  = colors.white
C_BORDER = colors.HexColor("#AAAAAA")

TNR        = "Times-Roman"
TNR_BOLD   = "Times-Bold"
TNR_ITALIC = "Times-Italic"


def _sanitize(name):
    name = name.strip()
    name = re.sub(r'[^\w\s-]', '', name)
    name = re.sub(r'[\s]+', '_', name)
    return name


def _style(name, font=TNR, size=10, color=C_BLACK,
           align=TA_CENTER, leading=14):
    return ParagraphStyle(
        name, fontName=font, fontSize=size,
        textColor=color, alignment=align, leading=leading,
    )


def _roll(sr):
    return f"EC31{sr:02d}"


def _footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setFillColor(C_LGRAY)
    canvas.rect(0, 0, w, 0.9 * cm, stroke=0, fill=1)
    canvas.setStrokeColor(C_BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(0, 0.9 * cm, w, 0.9 * cm)
    canvas.setFont(TNR_ITALIC, 8)
    canvas.setFillColor(C_DGRAY)
    canvas.drawString(
        1.5 * cm, 0.3 * cm,
        "Generated by ECE Student Management System — "
        "CSMSS Chh. Shahu College of Engineering"
    )
    canvas.drawRightString(
        w - 1.5 * cm, 0.3 * cm,
        f"Page {doc.page}  |  {date.today().strftime('%d %B %Y')}"
    )
    canvas.restoreState()


def generate_ct1_pdf_report(meta, data):
    from reportlab.platypus import Image

    buf = io.BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
    )

    story = []
    page_width = A4[0] - 3.0 * cm

    exam_label = meta.get("exam_label", meta.get("exam_type", "CT1"))
    max_marks = meta.get("max_marks", 10)
    pass_mark = max_marks * 0.4

    # ============================================================
    # STYLES
    # ============================================================
    s_title = _style(
        "title",
        font=TNR_BOLD,
        size=14,
        color=C_BLACK,
        align=TA_CENTER,
        leading=18,
    )

    s_dept = _style(
        "dept",
        font=TNR_BOLD,
        size=10,
        color=C_BLACK,
        align=TA_CENTER,
        leading=14,
    )

    s_label = _style(
        "label",
        font=TNR_BOLD,
        size=8,
        color=C_BLACK,
        align=TA_LEFT,
        leading=12,
    )

    s_value = _style(
        "value",
        font=TNR,
        size=8,
        color=C_BLACK,
        align=TA_LEFT,
        leading=12,
    )

    s_th = _style(
        "th",
        font=TNR_BOLD,
        size=8,
        color=C_BLACK,
        align=TA_CENTER,
        leading=11,
    )

    s_td = _style(
        "td",
        font=TNR,
        size=8,
        color=C_BLACK,
        align=TA_CENTER,
        leading=11,
    )

    s_td_l = _style(
        "tdl",
        font=TNR,
        size=8,
        color=C_BLACK,
        align=TA_LEFT,
        leading=11,
    )

    s_sig = _style(
        "sig",
        font=TNR_BOLD,
        size=9,
        color=C_BLACK,
        align=TA_CENTER,
        leading=13,
    )

    # ============================================================
    # LOGO HEADER
    # ============================================================
    left_logo = (
        Image(LEFT_LOGO, width=55, height=55)
        if os.path.exists(LEFT_LOGO)
        else ""
    )

    right_logo = (
        Image(RIGHT_LOGO, width=55, height=55)
        if os.path.exists(RIGHT_LOGO)
        else ""
    )

    header = Table(
        [[
            left_logo,
            Paragraph(
                "Chhatrapati Shahu Maharaj Shikshan Sanstha's<br/>"
                "CSMSS Chh. Shahu College of Engineering<br/>"
                "Kanchanwadi, Chhatrapati Sambhajinagar",
                s_title
            ),
            right_logo
        ]],
        colWidths=[2 * cm, page_width - 4 * cm, 2 * cm]
    )

    header.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1, C_BLACK),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))

    story.append(header)

    dept_tab = Table(
        [[Paragraph(
            "Department of Electronics and Computer Engineering",
            s_dept
        )]],
        colWidths=[page_width]
    )

    dept_tab.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1, C_BLACK),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))

    story.append(dept_tab)
    story.append(Spacer(1, 8))

    # ============================================================
    # META
    # ============================================================
    cw = page_width / 6
    meta_widths = [cw * 0.8, cw * 1.2] * 3

    meta_data = [
        [
            Paragraph("Subject Code", s_label),
            Paragraph(meta["subject_code"], s_value),
            Paragraph("Subject Name", s_label),
            Paragraph(meta["subject_name"], s_value),
            Paragraph("Exam Type", s_label),
            Paragraph(exam_label, s_value),
        ],
        [
            Paragraph("Subject Teacher", s_label),
            Paragraph(meta["subject_teacher"], s_value),
            Paragraph("Exam Date", s_label),
            Paragraph(meta["exam_date"], s_value),
            Paragraph("", s_value),
            Paragraph("", s_value),
        ]
    ]

    info_tab = Table(meta_data, colWidths=meta_widths)

    info_tab.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 1, C_BLACK),
        ("SPAN", (4, 1), (5, 1)),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))

    story.append(info_tab)
    story.append(Spacer(1, 10))

    # ============================================================
    # MARKS TABLE
    # ============================================================
    headers = [
        Paragraph("Sr No", s_th),
        Paragraph("Roll No", s_th),
        Paragraph("PRN No", s_th),
        Paragraph("Student Name", s_th),
        Paragraph(f"Marks ({max_marks})", s_th),
    ]

    widths = [
        page_width * 0.08,
        page_width * 0.12,
        page_width * 0.22,
        page_width * 0.38,
        page_width * 0.20,
    ]

    table_data = [headers]
    marks = []

    for d in data:
        val = "AB" if d["ct1"] is None else str(d["ct1"])

        if d["ct1"] is not None:
            marks.append(d["ct1"])

        table_data.append([
            Paragraph(str(d["sr"]), s_td),
            Paragraph(_roll(d["sr"]), s_td),
            Paragraph(str(d["prn"]), s_td),
            Paragraph(str(d["name"]), s_td_l),
            Paragraph(val, s_td),
        ])

    tab = Table(table_data, colWidths=widths, repeatRows=1)

    tab.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 1, C_BLACK),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))

    story.append(tab)
    story.append(Spacer(1, 12))

    # ============================================================
    # ANALYSIS
    # ============================================================
    total = len(data)
    present = len(marks)
    absent = total - present
    passed = sum(1 for m in marks if m >= pass_mark)
    failed = present - passed

    avg = round(sum(marks) / present, 2) if present else 0
    med = round(statistics.median(marks), 2) if marks else 0
    high = max(marks) if marks else 0
    low = min(marks) if marks else 0

    analysis = Table([
        [
            "Total",
            "Present",
            "Absent",
            "Pass",
            "Fail",
            "Average",
            "Median",
            "High",
            "Low",
        ],
        [
            str(total),
            str(present),
            str(absent),
            str(passed),
            str(failed),
            str(avg),
            str(med),
            str(high),
            str(low),
        ]
    ], colWidths=[page_width / 9] * 9)

    analysis.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 1, C_BLACK),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))

    story.append(analysis)
    story.append(Spacer(1, 30))

    # ============================================================
    # SIGNATURES
    # ============================================================
    sig_tab = Table([[
        Paragraph("Subject Teacher", s_sig),
        Paragraph("Prof. A. V. Khake<br/>Class Teacher", s_sig),
        Paragraph("Dr. D. L. Bhuyar<br/>HOD", s_sig),
    ]], colWidths=[page_width / 3] * 3)

    sig_tab.setStyle(TableStyle([
        ("LINEABOVE", (0, 0), (-1, -1), 1, C_BLACK),
        ("TOPPADDING", (0, 0), (-1, -1), 18),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))

    story.append(sig_tab)

    # ============================================================
    # BUILD
    # ============================================================
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)

    buf.seek(0)

    filename = (
        f"{_sanitize(meta['subject_name'])}_"
        f"{meta.get('exam_type','CT1')}_Report.pdf"
    )

    return buf, filename


def _fmt_mark(v):
    if v is None:
        return ""
    fv = float(v)
    if fv == int(fv):
        return str(int(fv))
    return str(fv)


# ══════════════════════════════════════════════════════════════
#  INTERNAL MARKS REPORT — PDF
# ══════════════════════════════════════════════════════════════
def generate_internal_pdf(meta, data):
    buf = io.BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
    )

    story = []
    page_width = A4[0] - 3.0 * cm

    # ─────────────────────────────────────────────
    # Styles (BLACK / PRINT FRIENDLY)
    # ─────────────────────────────────────────────
    s_college = _style(
        "int_college",
        font=TNR_BOLD,
        size=14,
        color=C_BLACK,
        align=TA_CENTER,
        leading=18,
    )

    s_dept = _style(
        "int_dept",
        font=TNR_BOLD,
        size=10,
        color=C_BLACK,
        align=TA_CENTER,
        leading=14,
    )

    s_label = _style(
        "int_label",
        font=TNR_BOLD,
        size=8,
        color=C_BLACK,
        align=TA_LEFT,
        leading=12,
    )

    s_value = _style(
        "int_value",
        font=TNR,
        size=8,
        color=C_BLACK,
        align=TA_LEFT,
        leading=12,
    )

    s_th = _style(
        "int_th",
        font=TNR_BOLD,
        size=7,
        color=C_BLACK,
        align=TA_CENTER,
        leading=10,
    )

    s_td = _style(
        "int_td",
        font=TNR,
        size=7,
        color=C_BLACK,
        align=TA_CENTER,
        leading=10,
    )

    s_td_l = _style(
        "int_tdl",
        font=TNR,
        size=7,
        color=C_BLACK,
        align=TA_LEFT,
        leading=10,
    )

    s_sig = _style(
        "int_sig",
        font=TNR_BOLD,
        size=9,
        color=C_BLACK,
        align=TA_CENTER,
        leading=13,
    )

    # ─────────────────────────────────────────────
    # Header with Logos
    # ─────────────────────────────────────────────
    left_logo = (
        Image(LEFT_LOGO, width=55, height=55)
        if os.path.exists(LEFT_LOGO)
        else ""
    )

    right_logo = (
        Image(RIGHT_LOGO, width=55, height=55)
        if os.path.exists(RIGHT_LOGO)
        else ""
    )


    header = Table(
        [[
            left_logo,
            Paragraph("CSMSS Chh. Shahu College of Engineering", s_college),
            right_logo
        ]],
        colWidths=[1.8 * cm, page_width - 3.6 * cm, 1.8 * cm]
    )

    header.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1.2, colors.black),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (1, 0), (1, 0), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))

    story.append(header)

    dept_tab = Table(
        [[Paragraph(
            "Department of Electronics and Computer Engineering",
            s_dept
        )]],
        colWidths=[page_width],
    )

    dept_tab.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1.0, colors.black),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))

    story.append(dept_tab)
    story.append(Spacer(1, 8))

    # ─────────────────────────────────────────────
    # Metadata
    # ─────────────────────────────────────────────
    cw = page_width / 6
    col_widths_meta = [
        cw * 0.75,
        cw * 1.25,
        cw * 0.75,
        cw * 1.25,
        cw * 0.75,
        cw * 1.25,
    ]

    meta_data = [
        [
            Paragraph("Subject Code :", s_label),
            Paragraph(meta['subject_code'], s_value),
            Paragraph("Subject Name :", s_label),
            Paragraph(meta['subject_name'], s_value),
            Paragraph("Semester :", s_label),
            Paragraph(str(meta['semester_id']), s_value),
        ],
        [
            Paragraph("Academic Year :", s_label),
            Paragraph(meta['academic_year'], s_value),
            Paragraph("", s_value),
            Paragraph("", s_value),
            Paragraph("", s_value),
            Paragraph("", s_value),
        ],
    ]

    info_tab = Table(meta_data, colWidths=col_widths_meta)

    info_tab.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 1.0, colors.black),
        ("SPAN", (1, 1), (5, 1)),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))

    story.append(info_tab)
    story.append(Spacer(1, 8))

    # ─────────────────────────────────────────────
    # Marks Table
    # ─────────────────────────────────────────────
    headers = [
        "SR", "PRN", "NAME", "CT1", "CT2",
        "BEST CT", "ASSIGN", "CA", "MIDSEM", "INTERNAL"
    ]

    col_headers = [Paragraph(h, s_th) for h in headers]

    col_widths = [
        page_width * 0.05,
        page_width * 0.11,
        page_width * 0.19,
        page_width * 0.08,
        page_width * 0.08,
        page_width * 0.08,
        page_width * 0.09,
        page_width * 0.07,
        page_width * 0.08,
        page_width * 0.17,
    ]

    table_data = [col_headers]

    for d in data:
        table_data.append([
            Paragraph(str(d['sr']), s_td),
            Paragraph(str(d['prn']), s_td),
            Paragraph(str(d['name']), s_td_l),
            Paragraph(_fmt_mark(d['ct1']), s_td),
            Paragraph(_fmt_mark(d['ct2']), s_td),
            Paragraph(_fmt_mark(d['best_ct']), s_td),
            Paragraph(_fmt_mark(d['assignment']), s_td),
            Paragraph(_fmt_mark(d['ca']), s_td),
            Paragraph(_fmt_mark(d['midsem']), s_td),
            Paragraph(_fmt_mark(d['internal']), s_td),
        ])

    marks_tab = Table(
        table_data,
        colWidths=col_widths,
        repeatRows=1
    )

    marks_tab.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.8, colors.black),
        ("BOX", (0, 0), (-1, -1), 1.2, colors.black),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))

    story.append(marks_tab)

    story.append(Spacer(1, 30))

    # ─────────────────────────────────────────────
    # Signatures
    # ─────────────────────────────────────────────
    sig_tab = Table(
        [[
            Paragraph("Subject Teacher", s_sig),
            Paragraph("Prof. A. V. Khake<br/>Class Teacher", s_sig),
            Paragraph("Dr. D. L. Bhuyar<br/>HOD", s_sig),
        ]],
        colWidths=[page_width / 3] * 3,
    )

    sig_tab.setStyle(TableStyle([
        ("LINEABOVE", (0, 0), (-1, -1), 1.0, colors.black),
        ("LINEBEFORE", (1, 0), (1, -1), 0.8, colors.black),
        ("LINEBEFORE", (2, 0), (2, -1), 0.8, colors.black),
        ("TOPPADDING", (0, 0), (-1, -1), 22),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))

    story.append(sig_tab)

    # ─────────────────────────────────────────────
    # Build PDF
    # ─────────────────────────────────────────────
    doc.build(
        story,
        onFirstPage=_footer,
        onLaterPages=_footer
    )

    buf.seek(0)

    subj_clean = _sanitize(meta['subject_name'])
    ay_clean = meta['academic_year'].replace('-', '_')

    filename = (
        f"{subj_clean}_Internal_"
        f"Sem{meta['semester_id']}_{ay_clean}.pdf"
    )

    return buf, filename

# ══════════════════════════════════════════════════════════════
#  DEPARTMENT CT1 SUMMARY REPORT — PDF
#  Append after all existing functions in pdf_utils.py
# ══════════════════════════════════════════════════════════════
def generate_ct1_summary_pdf(summary_data):
    """
    Department CT1 Summary PDF
    Excel-style clean formatting
    """

    import io as _io
    from reportlab.lib.pagesizes import landscape, A4
    from reportlab.lib import colors
    from reportlab.lib.units import cm
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer,
        Table, TableStyle, Image
    )

    meta      = summary_data["report_meta"]
    cls_sum   = summary_data["class_summary"]
    subjects  = summary_data["subjects"]
    fac_table = summary_data["faculty_table"]
    sigs      = summary_data["signatories"]

    n_subjects = len(subjects)

    buf = _io.BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=landscape(A4),
        leftMargin=1.2*cm,
        rightMargin=1.2*cm,
        topMargin=1.2*cm,
        bottomMargin=1.2*cm
    )

    page_w = landscape(A4)[0]
    usable_w = page_w - 2.4*cm

    # ==========================
    # COLORS
    # ==========================
    BK = colors.black
    RED_AB = colors.HexColor("#FFE5E5")
    WHITE = colors.white

    # ==========================
    # STYLES
    # ==========================
    def _s(name,size=9,bold=False,align=TA_CENTER):
        return ParagraphStyle(
            name=name,
            fontName="Times-Bold" if bold else "Times-Roman",
            fontSize=size,
            alignment=align,
            textColor=BK,
            leading=size+3
        )

    s_title  = _s("t",13,True)
    s_head   = _s("h",9,True)
    s_cell   = _s("c",8)
    s_left   = _s("l",8,False,TA_LEFT)
    s_bold   = _s("b",8,True)
    s_sig    = _s("sig",8,True)

    story=[]

    # ==========================
    # LOGO HEADER
    # ==========================
    if os.path.exists(LEFT_LOGO):
        left_logo = Image(LEFT_LOGO, width=55, height=55)
    else:
        left_logo = ""

    if os.path.exists(RIGHT_LOGO):
        right_logo = Image(RIGHT_LOGO, width=55, height=55)
    else:
        right_logo = ""

    header = Table([
        [
            left_logo,
            Paragraph(
                "Chhatrapati Shahu Maharaj Shikshan Sanstha's<br/>"
                "CSMSS Chh. Shahu College of Engineering<br/>"
                "Kanchanwadi, Chhatrapati Sambhajinagar<br/>"
                "Department of Electronics and Computer Engineering",
                s_title
            ),
            right_logo
        ]
    ], colWidths=[2*cm, usable_w-4*cm, 2*cm])

    header.setStyle(TableStyle([
        ("BOX",(0,0),(-1,-1),1,BK),
        ("ALIGN",(0,0),(-1,-1),"CENTER"),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE")
    ]))

    story.append(header)
    story.append(Spacer(1,8))

    # ==========================
    # REPORT TITLE
    # ==========================
    title = Table([
        [Paragraph(meta["report_title"],s_head)]
    ],colWidths=[usable_w])

    title.setStyle(TableStyle([
        ("BOX",(0,0),(-1,-1),1,BK)
    ]))

    story.append(title)

    # ==========================
    # META
    # ==========================
    meta_tab = Table([
        [
            Paragraph(f"Academic Year : {meta['academic_year']}",s_left),
            Paragraph(f"Date : {meta['date_range']}",s_left)
        ],
        [
            Paragraph(f"Class : {cls_sum['class_name']}",s_left),
            Paragraph(f"Division : {cls_sum['division']}",s_left)
        ]
    ],colWidths=[usable_w/2]*2)

    meta_tab.setStyle(TableStyle([
        ("GRID",(0,0),(-1,-1),1,BK)
    ]))

    story.append(meta_tab)
    story.append(Spacer(1,8))

    # ==========================
    # SUBJECT TABLE
    # ==========================
    label_w = usable_w*0.20
    subj_w=(usable_w-label_w)/n_subjects

    table_data=[]

    table_data.append(
        [Paragraph("Subject Name",s_bold)] +
        [Paragraph(s["abbr"],s_bold) for s in subjects]
    )

    table_data.append(
        [Paragraph("Full Subject Name",s_bold)] +
        [Paragraph(s["name"],s_cell) for s in subjects]
    )

    stats=[
        ("appeared","Appeared Students"),
        ("passed","Passed Students"),
        ("absent","Absent"),
        ("failed","Failed")
    ]

    for key,label in stats:
        row=[Paragraph(label,s_bold)]

        for s in subjects:
            row.append(Paragraph(str(s[key]),s_cell))

        table_data.append(row)

    table_data.append(
        [Paragraph("Subject Percentage Result",s_bold)] +
        [Paragraph(f"{s['result_pct']}%",s_bold) for s in subjects]
    )

    stats_tab=Table(
        table_data,
        colWidths=[label_w]+[subj_w]*n_subjects
    )

    style=[
        ("GRID",(0,0),(-1,-1),1,BK),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("ALIGN",(0,0),(-1,-1),"CENTER")
    ]

    absent_row=4
    style.append(
        ("BACKGROUND",(1,absent_row),(-1,absent_row),RED_AB)
    )

    stats_tab.setStyle(TableStyle(style))

    story.append(stats_tab)
    story.append(Spacer(1,10))

    # ==========================
    # FACULTY TABLE
    # ==========================
    fac_data=[
        [
            Paragraph("Abbreviation",s_bold),
            Paragraph("Full Subject Name",s_bold),
            Paragraph("Faculty",s_bold)
        ]
    ]

    for f in fac_table:
        fac_data.append([
            Paragraph(f["abbr"],s_cell),
            Paragraph(f["name"],s_left),
            Paragraph(f["faculty"],s_left)
        ])

    fac_tab=Table(
        fac_data,
        colWidths=[
            usable_w*0.15,
            usable_w*0.50,
            usable_w*0.35
        ]
    )

    fac_tab.setStyle(TableStyle([
        ("GRID",(0,0),(-1,-1),1,BK)
    ]))

    story.append(fac_tab)
    story.append(Spacer(1,20))

    # ==========================
    # SIGNATURES
    # ==========================
    sig_data=[[
        Paragraph(
            f"{sigs['coordinator']}<br/>Class Test Coordinator",
            s_sig
        ),
        Paragraph(
            f"{sigs['hod']}<br/>HOD",
            s_sig
        ),
        Paragraph(
            f"{sigs['dean']}<br/>Dean Academics",
            s_sig
        ),
        Paragraph(
            f"{sigs['principal']}<br/>Principal",
            s_sig
        )
    ]]

    sig_tab=Table(sig_data,colWidths=[usable_w/4]*4)

    sig_tab.setStyle(TableStyle([
        ("LINEABOVE",(0,0),(-1,-1),1,BK),
        ("TOPPADDING",(0,0),(-1,-1),18)
    ]))

    story.append(sig_tab)

    # ==========================
    # BUILD
    # ==========================
    doc.build(story)

    buf.seek(0)

    filename=(
        f"{cls_sum['class_name'].replace(' ','')}_"
        f"{meta['exam_type']}_Summary_"
        f"{meta['academic_year'].replace('-','_')}.pdf"
    )

    return buf,filename